### PR TITLE
New web UI based on Talking Michif Dictionary

### PR DESCRIPTION
**Pull request by dhdaines**
This is minimally ready for review!  There are a couple of little bugs still and the layout could be tweaked further.

### CODE REVIEW

**Comment by dhdaines** [comment]
The deploy-preview URL doesn't seem to actually work ... I don't understand how to make it work so I'll let you deal with that :)

**Review by roedoejet — CHANGES_REQUESTED** [review]
Hey @dhdaines - this is awesome, thanks so much! I've made a few small changes in https://github.com/MotherTongues/mothertongues-UI/pull/7 and https://github.com/MotherTongues/mothertongues-UI/pull/8 that I would like to merge first (rebase merge #8 onto #7 first if you do it through GitHub).  There are a lot of commits here, so once we merge #7 and #8, I think we should squash merge this into main.

Thanks again!

**Comment by dhdaines** [comment]
> Hey @dhdaines - this is awesome, thanks so much! I've made a few small changes in #7 and #8 that I would like to merge first (rebase merge #8 onto #7 first if you do it through GitHub). There are a lot of commits here, so once we merge #7 and #8, I think we should squash merge this into main.

Yes, squashing would be a good idea!  I'll see if I can make the fix to the sampling I mentioned in #7 but it seems like I should probably merge both of them first to avoid formatting issues.

**Comment by dhdaines** [comment]
I think this is okay to merge now, though we can still improve it in a separate PR, it works well.

**Pull request merged**
